# Generated by Django 2.2.1 on 2019-05-15 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=200, verbose_name='Hotel')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('raw_data', models.TextField(verbose_name='Data')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
        ),
    ]
