version: '3.7'

services:

  # The application
  app:
    build:
      context: .
    image: &app app
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  # Database
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'

  # The Celery worker
  celery:
    build: .
    image: *app
    user: python
    restart: 'no'
    environment:
      - CELERY_BROKER=${CELERY_BROKER}
    command: celery -A worker_celery worker --concurrency=20 --loglevel=DEBUG
    volumes:
      - ./app:/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  # Celery monitoring
  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    restart: 'no'
    environment:
      - FLOWER_BROKER=${FLOWER_BROKER}
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq

  # RabbitMQ message broker for Celery
  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
